---
- hosts: spine
  become: yes
  gather_facts: no
  tasks:
  - name: bring up Spine01/02 interfaces
    nclu:
     commands:
         - add interface swp1-4
     commit: true

- hosts: leaf
  become: yes
  gather_facts: no
  tasks:
  - name: bring up Leaf01-04 interfaces
    nclu:
     commands:
       - add interface swp1-2,swp48-52
     commit: true

- hosts: leaf:spine
  become: yes
  gather_facts: no
  tasks:
  - name: copy topology.dot file to /etc/ptm.d on all switches
    copy:
      src: ./topology.dot
      dest: /etc/ptm.d
      force: yes
  - name: restart ptmd service
    service:
      name: ptmd
      state: restarted

- hosts: host
  become: yes
  gather_facts: no
  tasks:
  - name: "Install LLDP and SNMP"
    apt: name={{ item }} state=present
    update_cache: yes
    with_items:
       - lldpd
       - snmp
       - snmpd

  - name: "Start and enable the LLDP and SNMP services"
    service: name={{ item }} state=started enabled=yes
    with_items:
       - lldpd
       - snmpd

  - name: "modify /e/n/i to add eth1 and eth2"
    blockinfile:
      dest: /etc/network/interfaces
      block: |
        auto eth1
        iface eth1 inet dhcp
        auto eth2
        iface eth2 inet dhcp
      backup: yes    

  - name: "bring up eth1 and eth2"
    shell: ip link set dev eth1 up && ip link set dev eth2 up
