---
- hosts: spine
  become: yes
  gather_facts: no
  tasks:
  - name: bring up Spine01/02 interfaces
    nclu:
     commands:
         - add interface swp1-4
     commit: true

- hosts: leaf
  become: yes
  gather_facts: no
  tasks:
  - name: bring up Leaf01-04 interfaces
    nclu:
     commands:
       - add interface swp1-2,swp48-52
     commit: true

- hosts: leaf:spine
  become: yes
  gather_facts: no
  tasks:
  - name: copy topology.dot file to /etc/ptm.d on all switches
    copy:
      src: ./topology.dot
      dest: /etc/ptm.d
      force: yes
  - name: restart ptmd service
    service:
      name: ptmd
      state: restarted

- hosts: host
  remote_user: cumulus
  become: yes
  become_method: sudo
  tasks:
  - name: "Install LLDP and SNMP"
    apt: name={{ item }} state=present
    with_items:
      - lldp
      - snmp

  - name: "Start and enable the LLDP and SNMP services"
    service: name={{ item }} state=started enabled=yes
    with_items:
       - lldp
       - snmp
    